HE_Mesh: wblut.hemesh.HEM_TriangulateMT Class Reference
wblut.hemesh.HEM_TriangulateMT Class Reference
Classes
class TriangulateRunner
Public Member Functions
HEM_TriangulateMT ()
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
HE_Selection triangles
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Member Functions
void triangulateNoPairing (final HE_Face face, final HE_Mesh mesh, final int[] tris)
List< int[]> triangulate (final List< HE_Face > faces)
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_TriangulateMT.HEM_TriangulateMT ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_TriangulateMT.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_MeshStructure.faces, wblut.hemesh.HE_MeshStructure.fItr(), wblut.hemesh.HE_MeshStructure.getNumberOfFaces(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_MeshStructure.pairHalfedges(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HEM_TriangulateMT.triangulate(), and wblut.hemesh.HEM_TriangulateMT.triangulateNoPairing().
HE_Mesh wblut.hemesh.HEM_TriangulateMT.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_MeshStructure.clearFaces(), wblut.hemesh.HE_MeshStructure.faces, wblut.hemesh.HE_MeshStructure.fItr(), wblut.hemesh.HE_MeshStructure.getNumberOfFaces(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_MeshStructure.pairHalfedges(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HEM_TriangulateMT.triangulate(), and wblut.hemesh.HEM_TriangulateMT.triangulateNoPairing().
List<int[]> wblut.hemesh.HEM_TriangulateMT.triangulate (final List< HE_Face > faces) private
Parameters
faces
Returns
void wblut.hemesh.HEM_TriangulateMT.triangulateNoPairing (final HE_Face face, final HE_Mesh mesh, final int[] tris) private
Parameters
face
mesh
tris
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Face.getFaceHalfedges(), wblut.hemesh.HE_Face.getFaceUVWs(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_MeshStructure.setFace(), wblut.hemesh.HE_MeshStructure.setHalfedge(), wblut.hemesh.HE_MeshStructure.setNext(), wblut.hemesh.HE_Halfedge.setUVW(), and wblut.hemesh.HE_MeshStructure.setVertex().
Member Data Documentation
HE_Selection wblut.hemesh.HEM_TriangulateMT.triangles
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_TriangulateMT.java