HE_Mesh: wblut.hemesh.HET_Diagnosis Class Reference
wblut.hemesh.HET_Diagnosis Class Reference
Static Public Member Functions
static boolean isValidMesh (final HE_Mesh mesh)
static void stats (final HE_Mesh mesh)
static boolean isValidSurface (final HE_Mesh mesh)
static boolean validate (final HE_Mesh mesh)
static boolean validateSurface (final HE_Mesh mesh)
static boolean validate (final HE_Mesh mesh, final boolean verbose, final boolean force, final boolean allowSurface)
static void checkVertex (final HE_Vertex v, final HE_Mesh mesh)
static void checkFace (final HE_Face f, final HE_Mesh mesh)
static void checkHalfedges (final HE_MeshStructure mesh)
Detailed Description
The Class HET_Diagnosis.
Author
Frederik Vanhoutte, W:Blut
Member Function Documentation
static void wblut.hemesh.HET_Diagnosis.checkFace (final HE_Face f, final HE_Mesh mesh) static
Parameters
f
mesh
References wblut.hemesh.HE_MeshStructure.contains(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Element.getKey(), wblut.geom.WB_Vector.getLength3D(), wblut.hemesh.HE_Face.getNeighborFaces(), and wblut.hemesh.HE_Face.getTriangles().
static void wblut.hemesh.HET_Diagnosis.checkHalfedges (final HE_MeshStructure mesh) static
References wblut.hemesh.HE_MeshStructure.contains(), wblut.hemesh.HE_MeshStructure.edges, wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshStructure.halfedges, and wblut.hemesh.HE_MeshStructure.unpairedHalfedges.
static void wblut.hemesh.HET_Diagnosis.checkVertex (final HE_Vertex v, final HE_Mesh mesh) static
Parameters
v
mesh
References wblut.hemesh.HE_MeshStructure.contains(), wblut.hemesh.HE_Vertex.getFaceStar(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Element.getKey(), wblut.geom.WB_Vector.getLength3D(), wblut.hemesh.HE_Vertex.getUmbrellaAngle(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.getVertexArea(), wblut.hemesh.HE_Vertex.getVertexDegree(), and wblut.hemesh.HE_Vertex.getVertexNormal().
static boolean wblut.hemesh.HET_Diagnosis.isValidMesh (final HE_Mesh mesh) static
Check consistency of datastructure of closed mesh.
Parameters
mesh the mesh
Returns
true or false
References wblut.hemesh.HET_Diagnosis.validate().
static boolean wblut.hemesh.HET_Diagnosis.isValidSurface (final HE_Mesh mesh) static
Check consistency of datastructure of surface.
Parameters
mesh the mesh
Returns
true or false
References wblut.hemesh.HET_Diagnosis.validate().
static void wblut.hemesh.HET_Diagnosis.stats (final HE_Mesh mesh) static
Parameters
mesh
References wblut.hemesh.HE_MeshStructure.getNumberOfEdges(), wblut.hemesh.HE_MeshStructure.getNumberOfFaces(), wblut.hemesh.HE_MeshStructure.getNumberOfHalfedges(), and wblut.hemesh.HE_MeshStructure.getNumberOfVertices().
static boolean wblut.hemesh.HET_Diagnosis.validate (final HE_Mesh mesh) static
Check consistency of datastructure.
Parameters
mesh the mesh
Returns
true or false
static boolean wblut.hemesh.HET_Diagnosis.validate (final HE_Mesh mesh, final boolean verbose, final boolean force, final boolean allowSurface) static
Check consistency of datastructure.
Parameters
mesh the mesh
verbose true: print to console, HE.SILENT: no output
force true: full scan, HE.BREAK: stop on first error
allowSurface the allow surface
Returns
true or false
References wblut.hemesh.HE_MeshStructure.contains(), wblut.hemesh.HE_MeshStructure.fItr(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_MeshStructure.getNumberOfFaces(), wblut.hemesh.HE_MeshStructure.getNumberOfHalfedges(), wblut.hemesh.HE_MeshStructure.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_HalfedgeIterator.hasNext(), wblut.hemesh.HE_MeshStructure.heItr(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_HalfedgeIterator.next(), and wblut.hemesh.HE_MeshStructure.vItr().
static boolean wblut.hemesh.HET_Diagnosis.validateSurface (final HE_Mesh mesh) static
Validate surface.
Parameters
mesh the mesh
Returns
true, if successful
References wblut.hemesh.HET_Diagnosis.validate().
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_Diagnosis.java