HE_Mesh: wblut.hemesh.HEM_Triangulate Class Reference
wblut.hemesh.HEM_Triangulate Class Reference
Public Member Functions
HEM_Triangulate ()
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
HE_Selection triangles
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Member Functions
void triangulateNoPairing (final HE_Face face, final HE_Mesh mesh)
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_Triangulate.HEM_Triangulate ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Triangulate.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_MeshStructure.clearPair(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_MeshStructure.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.geom.WB_Vector.getLength3D(), wblut.hemesh.HE_MeshStructure.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_MeshStructure.pairHalfedges(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_MeshStructure.setHalfedge(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, and wblut.hemesh.HEM_Triangulate.triangulateNoPairing().
HE_Mesh wblut.hemesh.HEM_Triangulate.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_MeshStructure.clearFaces(), wblut.hemesh.HE_MeshStructure.clearPair(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_MeshStructure.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.geom.WB_Vector.getLength3D(), wblut.hemesh.HE_MeshStructure.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_MeshStructure.pairHalfedges(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_MeshStructure.setHalfedge(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, and wblut.hemesh.HEM_Triangulate.triangulateNoPairing().
void wblut.hemesh.HEM_Triangulate.triangulateNoPairing (final HE_Face face, final HE_Mesh mesh) private
Parameters
face
mesh
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_MeshStructure.clearPair(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceUVWs(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_MeshStructure.setFace(), wblut.hemesh.HE_MeshStructure.setHalfedge(), wblut.hemesh.HE_MeshStructure.setNext(), wblut.hemesh.HE_Halfedge.setUVW(), and wblut.hemesh.HE_MeshStructure.setVertex().
Member Data Documentation
HE_Selection wblut.hemesh.HEM_Triangulate.triangles
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Triangulate.java