HE_Mesh: wblut.hemesh.HEM_Soapfilm Class Reference
wblut.hemesh.HEM_Soapfilm Class Reference
Public Member Functions
HEM_Soapfilm setAutoRescale (final boolean b)
HEM_Soapfilm setIterations (final int r)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Member Functions
WB_Point minDirichletEnergy (final HE_Vertex v)
Private Attributes
boolean autoRescale
int iter
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Soapfilm.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.fitInAABB(), wblut.hemesh.HE_MeshStructure.getAABB(), wblut.hemesh.HE_Element.getKey(), wblut.hemesh.HE_Selection.getOuterVertices(), wblut.hemesh.HEM_Soapfilm.iter, wblut.hemesh.HEM_Soapfilm.minDirichletEnergy(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HE_Mesh.triangulate(), and wblut.hemesh.HE_MeshStructure.vItr().
HE_Mesh wblut.hemesh.HEM_Soapfilm.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Mesh.fitInAABB(), wblut.hemesh.HE_MeshStructure.getAABB(), wblut.hemesh.HE_Element.getKey(), wblut.hemesh.HE_Selection.getOuterVertices(), wblut.hemesh.HEM_Soapfilm.iter, wblut.hemesh.HEM_Soapfilm.minDirichletEnergy(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HE_Mesh.triangulate(), and wblut.hemesh.HE_MeshStructure.vItr().
WB_Point wblut.hemesh.HEM_Soapfilm.minDirichletEnergy (final HE_Vertex v) private
Parameters
v
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.divSelf(), wblut.geom.WB_GeometryOp3D.getCosAngleBetween(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
HEM_Soapfilm wblut.hemesh.HEM_Soapfilm.setAutoRescale (final boolean b)
Parameters
b
Returns
HEM_Soapfilm wblut.hemesh.HEM_Soapfilm.setIterations (final int r)
Parameters
r
Returns
Member Data Documentation
boolean wblut.hemesh.HEM_Soapfilm.autoRescale private
int wblut.hemesh.HEM_Soapfilm.iter private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Soapfilm.java